remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme

title: Who Really Carried?
description: Kill leaders, damage carries, and early-game prediction in professional League of Legends.
show_downloads: false

